# Generated by Django 4.2.23 on 2025-08-22 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('task_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_image', models.ImageField(upload_to='task_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tasks_lists_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello_app.tasklist')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_updated_by', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('task_attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_attachment', models.FileField(upload_to='task_attachment/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tasks_lists_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello_app.tasklist')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_updated_by', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
