# Generated by Django 4.2.23 on 2025-09-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='checklist_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
