# Generated by Django 5.2.4 on 2025-08-02 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0002_alter_board_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
