# Generated by Django 5.2.4 on 2025-07-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forgot_password_otp',
            new_name='ForgotPasswordOTP',
        ),
    ]
