# Generated by Django 4.2.23 on 2025-09-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0002_tasklist_checklist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='checklist_items',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
