# Generated by Django 4.2.23 on 2025-08-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
