# Generated by Django 4.2.23 on 2025-09-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0003_alter_tasklist_checklist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskimage',
            name='tasks_lists_id',
        ),
        migrations.RemoveField(
            model_name='taskimage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='taskimage',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
