# Generated by Django 5.2.4 on 2025-08-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0003_alter_taskattachment_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcard',
            name='is_completed',
            field=models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('complated', 'Complated')], default='pending', max_length=10),
        ),
    ]
