# Generated by Django 4.2.23 on 2025-08-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task_card',
        ),
    ]
