# Generated by Django 5.2.4 on 2025-08-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0005_alter_taskcard_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcard',
            name='is_completed',
            field=models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('complated', 'Complated')], default='pending', max_length=10),
        ),
    ]
