# Generated by Django 5.2.4 on 2025-08-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0006_alter_taskcard_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
