# Generated by Django 4.2.23 on 2025-08-08 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcard',
            name='is_completed',
            field=models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
