# Generated by Django 4.2.23 on 2025-08-12 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0008_alter_taskcard_is_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('tasklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('tasklist_title', models.CharField(max_length=200)),
                ('tasklist_description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_created_by', to=settings.AUTH_USER_MODEL)),
                ('task_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_lists', to='trello_app.taskcard')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
