# Generated by Django 4.2.23 on 2025-08-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0009_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcard',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
