# Generated by Django 4.2.23 on 2025-08-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0010_board_is_starred_taskcard_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
