# Generated by Django 4.2.23 on 2025-08-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0011_tasklist_is_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='is_starred',
        ),
    ]
