# Generated by Django 4.2.23 on 2025-08-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0012_remove_tasklist_is_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcard',
            name='due_date',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('team', 'Team')], default='private', max_length=10),
        ),
    ]
