# Generated by Django 4.2.23 on 2025-08-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0013_remove_taskcard_due_date_tasklist_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcard',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_cards', to='trello_app.board'),
        ),
    ]
