# Generated by Django 4.2.23 on 2025-08-18 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0014_alter_taskcard_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcard',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
