# Generated by Django 4.2.23 on 2025-08-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0015_remove_taskcard_assigned_to_tasklist_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to='trello_app.tasklist'),
        ),
        migrations.AddField(
            model_name='taskimage',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_images', to='trello_app.tasklist'),
        ),
    ]
