# Generated by Django 4.2.23 on 2025-08-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0016_taskattachment_task_list_taskimage_task_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskattachment',
            name='task_list',
        ),
        migrations.RemoveField(
            model_name='taskimage',
            name='task_list',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='label_color',
            field=models.CharField(default='green', max_length=20),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='priority',
            field=models.CharField(default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
